<?php

namespace AppBundle\Repository;

/**
 * HakAksesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HakAksesRepository extends \Doctrine\ORM\EntityRepository
{
}
