<?php

namespace AppBundle\Repository;

/**
 * MataKuliahRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MataKuliahRepository extends \Doctrine\ORM\EntityRepository
{
}
