<?php

namespace AppBundle\Repository;

/**
 * ModulRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModulRepository extends \Doctrine\ORM\EntityRepository
{
}
