<?php

namespace AppBundle\Repository;

/**
 * paket_soalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paket_soalRepository extends \Doctrine\ORM\EntityRepository
{
}
