<?php

namespace AppBundle\Repository;

/**
 * soalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class soalRepository extends \Doctrine\ORM\EntityRepository
{
}
